name: cafienne_pg
services:
  workspace:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspaces/getting-started
    ports:
      - 12378
    tty: true           # <- keeps container running
    networks:
      - dev
    # user: node
